CREATE TABLE IF NOT EXISTS products (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	price INT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
	id SERIAL PRIMARY KEY,
	status VARCHAR(100) NOT NULL,
	user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
	id SERIAL PRIMARY KEY,
	quantity INT NOT NULL,
    order_id BIGINT REFERENCES orders(id),
	product_id BIGINT REFERENCES products(id)
);